# Generated by Django 5.1.6 on 2025-02-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_id', models.CharField(max_length=255)),
                ('descricao_lancamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lancamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('tipo_lancamento', models.CharField(choices=[('C', 'Credito'), ('D', 'Debito'), ('P', 'Pix'), ('R', 'Reembolso'), ('S', 'Salario')], default='C', max_length=1)),
                ('parcelas', models.IntegerField()),
                ('valor', models.FloatField()),
                ('total', models.FloatField()),
                ('centro_custo', models.CharField(max_length=255)),
            ],
        ),
    ]
